Fix packages incompatibility with Apple M1 by defaulting to linux/amd64 containers
cmu-delphi/delphi-epidata pull request #1080
Opened 2023-02-09 17:02 UTC by minhkhul

### Summary

Due to [package incompatibility](https://github.com/Toblerity/Fiona/discussions/1071), this PR adjusts the Makefile to build and run affected containers using linux/amd64 by default.

2023-02-10 15:15 UTC, krivard approved these changes
Looks good, and thankyou for keeping the line lengths reasonable 🙏 

Verified running on my machine with these changes does not affect running time for `make all test`.

2023-02-10 15:51 UTC, melange396 requested changes
looks pretty good!  two things though:

- (**_nit_**) it helps readability and is a good convention to put a space before each line-continuation backslash.

- (_**todo**_) you should make the `--platform linux/amd64` optional so that non-m1 environments arent forced to use it by default -- platform auto-selection seems to work properly for all but the m1 mac environment.  you could make an `m1` argument to force this behavior (see the `pdb` argument for reference), or even use the output of the command `uname -smp` to make that determination for you.

2023-02-13 15:23 UTC, krivard requested changes
👍 fulfills request for command-line switch

probably the change to pdb handling was unintentional and can be fixed directly from the suggestion; if it was on purpose can you say more about what you need it to do?

2023-02-13 15:23 UTC, krivard commented on dev/local/Makefile
> +	override =--pdb
issue: variable name removed from assignment, likely by accident

```suggestion
	override pdb=--pdb
```

2023-02-13 15:32 UTC, melange396 submitted a review, later dismissed
fix the `pdb` thing, and it looks good!

2023-02-13 17:32 UTC, minhkhul commented
Improvement with uname use. No longer need optional param.

2023-02-13 17:54 UTC, melange396 approved these changes
automatic!  awesome!!!
i would put an `@echo` line inside your `ifeq` block that prints something like "Apple M1 environment detected, using 'linux/amd64' platform for compatibility", so that its more obvious that the alternative platform is being used.  but other than that, this is great!

2023-02-13 19:20 UTC, minhkhul commented
Added some code to notify user when M1 system is detected.
<img width="1139" alt="Screenshot 2023-02-13 at 2 20 10 PM" src="https://user-images.githubusercontent.com/118945681/218553484-8a7cd1ef-3ee9-40f1-8491-8cd80b3e2e97.png">

2023-02-13 19:21 UTC, melange396 approved these changes
excellent work!

2023-02-13 19:26 UTC, melange396 approved these changes

2023-02-13 19:43 UTC, krivard approved these changes
👍 great adjustments!

2023-02-13 19:44 UTC, merged