Add performance testing workflow
cmu-delphi/delphi-epidata pull request #1086
Opened 2023-02-15 20:55 UTC by rzats

**Prerequisites**:

- [X] Unless it is a documentation hotfix it should be merged against the `dev` branch
- [X] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [X] Build is successful
- [X] Code is cleaned up and formatted

### Summary

Implements an automatable system for on-demand stability tests based on [the scalability-testing-rig PRD](https://docs.google.com/document/d/1znDZgeuciLIdm4-SEVWqcpllmEH0p8FE5r3ZWqUXj2U/edit#).

This first version of the testing rig launches a GitHub Actions runner off of a pull request based on a set comment (`/run performance test`) and, in order-
- sets up WireGuard in order to access the staging Delphi database
- clones the delphi-epidata repo, switching it to the pull request's branch
- sets up an environment with various other repos similar to the [install.sh](https://github.com/cmu-delphi/delphi-epidata/blob/dev/dev/local/install.sh) script
- builds and runs an instance of the epidata web server + API
- runs [Locust](https://locust.io/), a performance testing toolkit, targeting the local API we just created with a runtime of 15 minutes and 10 users spawning at a rate of 1 per second:
```
--users 10 --spawn-rate 1 --headless -t 15m
```
- links to Locust's report (which is contained in stdout) by creating a comment on the original pull request.

**IMPORTANT:** a prerequisite for this to function is for several secrets to be added to the repository.

These are as follows - various WireGuard credentials needed to set up the connection:
```
WG_PERF_ENDPOINT
WG_PERF_ENDPOINT_PUBLIC_KEY
WG_PERF_IPS
WG_PERF_ALLOWED_IPS
WG_PERF_PRIVATE_KEY
```
and the staging database connection string, including username & password:
```
DB_CONN_STRING
```

2023-02-15 22:05 UTC, melange396 requested changes
looks pretty cool!  i had a couple little doc/naming things, but im mostly concerned with how much you might be able to take out of the repo cloning section.  `v4.py` is a straight copy out of the admin repository, correct?

2023-02-15 22:05 UTC, melange396 commented on .github/workflows/performance-tests.yml
> +          git clone https://github.com/cmu-delphi/github-deploy-repo
i think this can probably be removed?
```suggestion

```

2023-02-17 14:37 UTC, rzats commented
@melange396 applied the fixes!

`v4.py` and the sample of queries are both a copy from the private repo, yeah. We can also upload the larger query sample file to S3 or similar, and then download it in the GitHub Action; or `git clone` the private admin repo although this may run into issues with token permissions.

2023-02-17 14:56 UTC, melange396 approved these changes
looks good!

2023-02-17 14:59 UTC, merged