R/JS api clients to support POST requests
cmu-delphi/delphi-epidata pull request #328
Opened 2020-12-14 18:31 UTC by sgratzl

closes #317 

are there any automatic test setups which will test that?

2020-12-14 20:14 UTC, dfarrow0 commented
> are there any automatic test setups which will test that?

if you're meaning integration tests for js/r clients, then sadly no (at least that i'm aware of)

2020-12-14 20:16 UTC, dfarrow0 commented
thanks for taking this on! i noticed that you added js/html files to test the js client. how do you run this locally? i'd be happy to add instruction to the dev guide and possibly automate this.

2020-12-14 20:31 UTC, sgratzl commented
atm they are simple smoke tests. You open the HTML file in the browser and it should show two success messages. Same for the node script that you just run. We could think of using a proper testing framework like jest or simple based on `console.assert`

2020-12-14 22:41 UTC, krivard approved these changes
nice work! 

this lays the groundwork for adding a test runner; something that will output pass or fail with a docker command. out of scope for this PR but I'll make an issue for it.

2020-12-14 22:41 UTC, krivard commented on src/client/delphi_epidata.coffee
> +    method = if fullURL.length < 2048 then 'GET' else 'POST'
add a comment here about avoiding 414

2020-12-14 22:41 UTC, krivard commented on integrations/client/test_delphi_epidata.html
> +</script>
add newline at EOF

2020-12-14 22:41 UTC, krivard commented on integrations/client/test_delphi_epidata.js
> +Epidata.covidcast(cb, 'fb-survey', Array(1000).fill('raw_cli').join(','), 'day', 'state', '2020-12-01', 'ca');
add newline at EOF

2020-12-14 22:42 UTC, krivard requested changes
[wrong radio button]

2020-12-15 13:06 UTC, sgratzl commented on src/client/delphi_epidata.coffee
> +    method = if fullURL.length < 2048 then 'GET' else 'POST'
done

2020-12-15 13:06 UTC, sgratzl commented on integrations/client/test_delphi_epidata.html
> +</script>
done

2020-12-15 13:06 UTC, sgratzl commented on integrations/client/test_delphi_epidata.js
> +Epidata.covidcast(cb, 'fb-survey', Array(1000).fill('raw_cli').join(','), 'day', 'state', '2020-12-01', 'ca');
done

2020-12-15 18:57 UTC, krivard approved these changes

2020-12-15 18:57 UTC, merged