Support new wording of V4a "local health" item
cmu-delphi/delphi-epidata pull request #450
Opened 2021-03-16 18:46 UTC by nmdefries

In Wave 8, the second subitem of V4a was switched from asking about "Local health workers" to "Doctors and other health professionals you go to for medical care". This resulted in a sharp increase in reported trust that is misleading when the new and old versions are reported under the same signal name.

This change describes the new V4a "doctors" signal and discontinues the previous "local health" version.

2021-03-16 18:59 UTC, capnrefsmmat requested changes
one wording fix, otherwise good

2021-03-16 18:59 UTC, capnrefsmmat commented on docs/api/covidcast-signals/fb-survey.md
> +| `smoothed_wvaccine_likely_doctors` | Estimated percentage of respondents who would be more likely to get a COVID-19 vaccine if it were recommended to them health professionals they go to for medica
```suggestion
| `smoothed_wvaccine_likely_doctors` | Estimated percentage of respondents who would be more likely to get a COVID-19 vaccine if it were recommended to them by doctors and other health professionals they go to for medical care, among respondents who have not yet been vaccinated. This item was shown to respondents starting in Wave 8. <br/> **Earliest date available:** 2021-02-08 | V4 |
```

2021-03-16 19:16 UTC, capnrefsmmat approved these changes
looks good; let's merge when the reissue is done

2021-03-17 21:27 UTC, krivard commented
I believe this should be good to go

2021-03-17 21:38 UTC, merged