[flask]: add /covidcast/correlation endpoint
cmu-delphi/delphi-epidata pull request #484
Opened 2021-04-08 18:37 UTC by sgratzl

adds a new custom endpoint `/covidcast/correlation` which computes the correlation lag/r2 for a given date and window.

e.g.

http://localhost:5000/covidcast/correlation?reference=fb-survey:smoothed_cli&others=indicator-combination:confirmed_7dav_incidence_prop&geo=state:ny&date=20210401&window=20200101-20210402&lag=2

will result in: 

![image](https://user-images.githubusercontent.com/4129778/114079252-f4c4cb00-9877-11eb-8b6d-8c21a31e2925.png)

note: I just have limited local test data, so results may vary in your system

2021-04-20 23:20 UTC, chinandrew commented
Is `Indicator` in signal source supposed to be capitalized?

2021-04-20 23:42 UTC, sgratzl commented
> Is `Indicator` in signal source supposed to be capitalized?

that is just my local test system, I messed that up during my import of a sample dataset

2021-04-26 20:20 UTC, krivard requested changes
Small truthy error, otherwise good

2021-04-26 20:20 UTC, krivard commented on src/server/endpoints/covidcast.py
> +    lag = extract_integer("lag") or 28
(and would it be good to include these handlers in tests)

2021-04-27 12:25 UTC, sgratzl commented on src/server/endpoints/covidcast.py
> +    lag = extract_integer("lag") or 28
good catch

2021-04-27 16:58 UTC, krivard approved these changes
nice work!

2021-04-27 19:42 UTC, merged