[fb-survey] Describe and link contingency rollup files
cmu-delphi/delphi-epidata pull request #556
Opened 2021-05-21 22:54 UTC by nmdefries

Document contingency rollup files.

2021-05-24 14:05 UTC, capnrefsmmat commented
Is there any reason to provide access to the non-rollup files? The rollup files seem like they are strictly better.

2021-05-24 17:31 UTC, nmdefries commented
RE usefulness: If someone already has all the historical files, they could want to download only new data, although the rollup files, especially in compressed form, aren't huge.

> I'd advertise the rollup files first, and stick the non-rollup link somewhere obscure on the page.

I'll do this for now, but I can remove the individual files entirely if you think they definitely won't be useful.

2021-06-02 16:39 UTC, capnrefsmmat requested changes
Good to go with one change

2021-06-02 16:39 UTC, capnrefsmmat commented on docs/symptom-survey/contingency-tables.md
> +
I think if you move this description up a bit (before the naming of the non-rollup files), this is ready to merge

2021-06-02 22:51 UTC, capnrefsmmat approved these changes

2021-06-02 22:55 UTC, merged