#798 fix bad table
cmu-delphi/delphi-epidata pull request #952
Opened 2022-08-23 20:11 UTC by LeonLu2

1. reformat the table
2. combine the signal and 7-day signal columns to one column
3. remove the geography and resolution columns and add universal explain below the table to make the description column text more visible

2022-08-24 13:55 UTC, krivard requested changes
Preview:
![image](https://user-images.githubusercontent.com/1158666/186434301-cd1a6b38-2118-4b52-bc8e-0f4dd3b26d9d.png)

Please change the description text back to left alignment; center alignment is mismatched with the other pages and is difficult to read.

The raw counts and 7dav signals needn't be separated by newlines, and we should switch from ampersands to `and`; see [the CTIS page](https://github.com/cmu-delphi/delphi-epidata/blob/dev/docs/api/covidcast-signals/fb-survey.md) for an example.

2022-08-24 19:28 UTC, LeonLu2 commented
Sure, the changes are made and up-to-date. Is there any other issues related to the table?

2022-08-25 21:03 UTC, krivard commented
Great! Apply same fix to JHU and USAFacts.

2022-08-26 19:18 UTC, LeonLu2 commented
For the table issue, JHU and USAFacts pages are all fixed.

2022-08-26 21:30 UTC, krivard approved these changes
👍 🎉 Nice work!

2022-08-26 21:30 UTC, krivard commented on docs/api/covidcast-signals/hhs.md
> +| `sum_confirmed_suspected_admissions_covid_1d_prop` and `sum_confirmed_suspected_admissions_covid_1d_prop_7dav` | Sum of adult and pediatric confirmed and suspected COVID-19 hospital admissions occu
This fixes a whitespace problem in the rendered table
```suggestion
| `sum_confirmed_suspected_admissions_covid_1d_prop` and <br/> `sum_confirmed_suspected_admissions_covid_1d_prop_7dav` | Sum of adult and pediatric confirmed and suspected COVID-19 hospital admissions occurring each day, per 100,000 population. <br/> **Earliest date available:** 2019-12-31                                                            |
```

2022-08-26 21:31 UTC, krivard approved these changes
silly robot dismissed my approving review 🤖

2022-08-26 21:46 UTC, merged